Add support of Microchip AT24C32 and support of single chip for `EEPR…
peterhinch/micropython_eeprom pull request #13
Opened 2022-09-20 22:50 UTC by JFF-Bohdan

…OM` class

[Description]

Adds support of:

1. Microchip AT24C32 (4 KiB)
2. Support of single chip setup for `EEPROM` class when single chip has address is 0x57 so entire set of chips (1 chip in our case) addresses are not started from 0x50.

Example:

```python
from eeprom_i2c import EEPROM, T24C32

eeprom = PROM(machine.I2C(0), T24C32)
```

Improves tests implementation by adding dependency injection of `EEPROM` object used during testing with support of old use case when object had not been provided for testing.

Example (for AT24C32 connected to I2C0 of my Raspberry Pi Pico W) when we creating instance of `EEPROM` and then passing it to `full_test` and also providing proper block size for this chip:

```python
import machine
from eeprom_i2c import EEPROM, T24C32
from eep_i2c import full_test

def get_eep():
    return EEPROM(machine.I2C(0), T24C32)

def main():
    print("App started")

    print("Running tests")
    eep = get_eep()
    full_test(eep, block_size=32)
    print("App finished")

if __name__ == "__main__":
    main()
```

[Motivation]

Have DS3231 with soldered AT24C32 chip and want to use both RTC and EEPROM. In my case AT24C32 has 0x57 as it's address and `EEPROM` class refused to work with this setup.

[Testing]

Executed `full_test` from `eep_i2c` against AT24C32 (with address 0x57) connected to my Raspberry Pi Pico W.

Test code:

```python
import machine
from eeprom_i2c import EEPROM, T24C32
from eep_i2c import full_test

def get_eep():
    return EEPROM(machine.I2C(0), T24C32)

def main():
    print("App started")

    print("Running tests")
    eep = get_eep()
    full_test(eep, block_size=32)
    print("App finished")

if __name__ == "__main__":
    main()
```

2022-09-21 09:29 UTC, peterhinch requested changes
This PR is hard to review because it contains several categories of change:
 1. Changes to program logic.
 2. Changes to documentation contents.
 3. Changes to code styling.
 4. Changes to documentation formatting.
 5. Changes to `.gitignore`.

Further, some of the changes to code styling degrade PEP8-compliant formatting to formatting which is non-compliant. The solution here is to run `black` over the code.

Please re-submit with a PR containing code logic changes and matching documentation content changes only so I can review and test for regressions. I will run `black` over it and accept any formatting changes it performs.

If you want to amend the documentation styling and change other files please submit a separate PR which I will review on its merits.

2022-09-21 21:15 UTC, JFF-Bohdan commented
Hi Peter,

Hope you are doing well. Please find my commits with latest updates. I reverted some changes and tried to follow your style as much as possible. Please let me know if you want to change anything else.

Some of my changes (for example, spaces added for slicing) were introduced automatically by PyCharm IDE which tries to improve level of PEP8 support.

Hope you will find my recent changes relevant.

Have a good day.
Bohdan.

2022-09-22 09:12 UTC, peterhinch requested changes
I have now run [black](https://pypi.org/project/black/) over all Python files in this repo and pushed an update. 

For future reference if you believe you have detected non-compliance with PEP8 in any repo, it would save both you and the author work if you just posted a request for them to run `black`: this is the tool that is used by the MicroPython maintainers.

As far as I'm concerned the code is now PEP8 compliant. If PyCharm tries to change it, I would examine the changes against PEP8 and raise the error with PyCharm or `black`. One or other must be wrong!

Please submit a PR against the reformatted repo containing your logic changes.

2022-09-24 16:22 UTC, closed without merging

2022-09-24 16:37 UTC, JFF-Bohdan commented
I cancelled this PR request with idea to create new one with smaller changes suggested. Hope it will work for you.