Update eeprom_i2c.py
peterhinch/micropython_eeprom pull request #19
Opened 2023-10-13 13:56 UTC by puppet13th

allow to override addr and max_chips_count

there is PCF8563T rtc chip onboard  xiao expansion board that use 0x50 address that have conflicted with i2c_eeprom scan address.

2023-10-15 16:22 UTC, peterhinch requested changes
This is OK but please also update [i2c.md](https://github.com/peterhinch/micropython_eeprom/blob/master/eeprom/i2c/I2C.md).

2023-10-16 03:18 UTC, puppet13th commented
> This is OK but please also update [i2c.md](https://github.com/peterhinch/micropython_eeprom/blob/master/eeprom/i2c/I2C.md).

thank for the response. i will update [i2c.md] with some example code.

2023-10-16 07:10 UTC, puppet13th commented
hardware setup:
- [XIAO ESP32S3 Sense](https://www.seeedstudio.com/XIAO-ESP32S3-Sense-p-5639.html)
- [XIAO Expansion Board](https://www.seeedstudio.com/Seeeduino-XIAO-Expansion-board-p-4746.html)
- at24c32 x 2 pcs

there is 2 I2C device on XIAO Expansion Board:
1. SSD1306 i2c oled display at address 0x3c ( 60 )
2. PCF8563T i2c RTC clock at address 0x51 ( 81 )

at24c32 address set to 0x52( 82 )  and 0x53( 83 )

code example:
```py
from machine import Pin, SoftI2C
from eeprom_i2c import EEPROM

i2c = SoftI2C( sda=Pin( 5 ), scl=Pin( 6 ) )

print( i2c.scan() )

eeprom = EEPROM( i2c, 4096, addr=0x52 )

eeprom0 = EEPROM( i2c, 4096, addr=0x52, max_chips_count=1 ) # use chip individually
eeprom1 = EEPROM( i2c, 4096, addr=0x53, max_chips_count=1 ) # use chip individually
```

code output:
```
[60, 81, 82, 83]
2 chips detected. Total EEPROM size 8192bytes.
1 chips detected. Total EEPROM size 4096bytes.
1 chips detected. Total EEPROM size 4096bytes.
```

2023-10-16 12:00 UTC, merged

2023-10-16 12:01 UTC, peterhinch commented
Thanks for that, a useful enhancement.